### ISSUE TITLE
spring-cloud-gcp has many linkage errors. Check the validity.

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#592] opened 2019-04-30 19:03 UTC
There are many false positives when the enforcer rule checks spring-cloud-gcp as below. This is because of the class path missing optional/provided libraries. A design doc is created to tackle this issue (http://go/jdd-supplemental-classpath)

# Reproduce

```
git clone https://github.com/spring-cloud/spring-cloud-gcp.git
cd spring-cloud-gcp
git checkout linkage-checker
mvn verify
```
    

With `<fail>true</fail>` at pom.xml, `mvn verify` fails with many errors. Investigate the validity of them.

```
[ERROR] Linkage Checker rule found errors. Linkage error report:
spring-core-5.2.0.M1.jar (98 errors):
  reactor.core.publisher.BaseSubscriber is not found, referenced from org.springframework.core.io.buffer.DataBufferUtils$WriteCompletionHandler
  reactor.core.publisher.FluxSink is not found, referenced from org.springframework.core.io.buffer.DataBufferUtils$WriteCompletionHandler
  reactor.core.publisher.SynchronousSink is not found, referenced from org.springframework.core.io.buffer.DataBufferUtils$ReadableByteChannelGenerator
  reactor.core.publisher.FluxSink is not found, referenced from org.springframework.core.io.buffer.DataBufferUtils$ReadCompletionHandler
  reactor.core.publisher.BaseSubscriber is not found, referenced from org.springframework.core.io.buffer.DataBufferUtils$WritableByteChannelSubscriber
  reactor.core.publisher.FluxSink is not found, referenced from org.springframework.core.io.buffer.DataBufferUtils$WritableByteChannelSubscriber
  io.netty.buffer.CompositeByteBuf is not found, referenced from org.springframework.core.io.buffer.NettyDataBufferFactory
  io.netty.buffer.ByteBufAllocator is not found, referenced from org.springframework.core.io.buffer.NettyDataBufferFactory
  io.netty.buffer.Unpooled is not found, referenced from org.springframework.core.io.buffer.NettyDataBufferFactory
  io.netty.buffer.ByteBuf is not found, referenced from org.springframework.core.io.buffer.NettyDataBufferFactory
...
  kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull is not found, referenced from org.springframework.core.env.PropertyResolverExtensionsKt
  kotlin.jvm.internal.Intrinsics.reifiedOperationMarker is not found, referenced from org.springframework.core.env.PropertyResolverExtensionsKt
  kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull is not found, referenced from org.springframework.core.env.PropertyResolverExtensionsKt

...
spring-context-5.2.0.M1.jar (158 errors):
  org.springframework.instrument.InstrumentationSavingAgent is not found, referenced from org.springframework.instrument.classloading.InstrumentationLoadTimeWeaver$InstrumentationAccessor
  javax.enterprise.concurrent.ManagedExecutors is not found, referenced from org.springframework.scheduling.concurrent.ConcurrentTaskExecutor$ManagedTaskBuilder
  javax.enterprise.concurrent.ManagedScheduledExecutorService is not found, referenced from org.springframework.scheduling.concurrent.ConcurrentTaskScheduler$EnterpriseConcurrentTriggerScheduler
  javax.enterprise.concurrent.Trigger is not found, referenced from org.springframework.scheduling.concurrent.ConcurrentTaskScheduler$EnterpriseConcurrentTriggerScheduler$1
  javax.enterprise.concurrent.LastExecution is not found, referenced from org.springframework.scheduling.concurrent.ConcurrentTaskScheduler$EnterpriseConcurrentTriggerScheduler$1
  groovy.lang.GroovyObject is not found, referenced from org.springframework.context.support.GenericGroovyApplicationContext
  groovy.lang.GroovySystem is not found, referenced from org.springframework.context.support.GenericGroovyApplicationContext
  groovy.lang.MetaClassRegistry is not found, referenced from org.springframework.context.support.GenericGroovyApplicationContext
...
slf4j-api-1.7.26.jar (2 errors):
  org.slf4j.impl.StaticMarkerBinder.getSingleton is not found, referenced from org.slf4j.MarkerFactory
  org.slf4j.impl.StaticMDCBinder.getSingleton is not found, referenced from org.slf4j.MDC

mockito-core-2.25.1.jar (2 errors):
  org.mockito.internal.creation.bytebuddy.inject.MockMethodDispatcher is not found, referenced from org.mockito.internal.creation.bytebuddy.MockMethodAdvice$ForReadObject
  org.mockito.internal.creation.bytebuddy.inject.MockMethodDispatcher is not found, referenced from org.mockito.internal.creation.bytebuddy.MockMethodAdvice$ForEquals
  org.mockito.internal.creation.bytebuddy.inject.MockMethodDispatcher is not found, referenced from org.mockito.internal.creation.bytebuddy.MockMethodAdvice$SerializableRealMethodCall
  org.mockito.internal.creation.bytebuddy.inject.MockMethodDispatcher is not found, referenced from org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator
...
google-http-client-1.28.0.jar (5 errors):
  org.apache.http.impl.client.DefaultHttpClient is not found, referenced from com.google.api.client.testing.http.apache.MockHttpClient
  org.apache.http.message.BasicHttpResponse is not found, referenced from com.google.api.client.testing.http.apache.MockHttpClient$1
  org.apache.http.client.RequestDirector is not found, referenced from com.google.api.client.testing.http.apache.MockHttpClient$1
  org.apache.http.HttpException is not found, referenced from com.google.api.client.testing.http.apache.MockHttpClient$1
  org.apache.http.HttpVersion is not found, referenced from com.google.api.client.testing.http.apache.MockHttpClient$1
  org.apache.http.impl.client.DefaultHttpClient.<init> is not found, referenced from com.google.api.client.testing.http.apache.MockHttpClient
  org.apache.http.message.BasicHttpResponse.<init> is not found, referenced from com.google.api.client.testing.http.apache.MockHttpClient$1
  org.apache.http.HttpVersion.HTTP_1_1 is not found, referenced from com.google.api.client.testing.http.apache.MockHttpClient$1

...

byte-buddy-agent-1.9.12.jar (2 errors):
  org.newsclub.net.unix.AFUNIXSocket is not found, referenced from net.bytebuddy.agent.VirtualMachine$ForHotSpot$OnUnix
  org.newsclub.net.unix.AFUNIXSocketAddress is not found, referenced from net.bytebuddy.agent.VirtualMachine$ForHotSpot$OnUnix
  org.newsclub.net.unix.AFUNIXSocket.isSupported is not found, referenced from net.bytebuddy.agent.VirtualMachine$ForHotSpot$OnUnix
  org.newsclub.net.unix.AFUNIXSocket.newInstance is not found, referenced from net.bytebuddy.agent.VirtualMachine$ForHotSpot$OnUnix
  org.newsclub.net.unix.AFUNIXSocket.setSoTimeout is not found, referenced from net.bytebuddy.agent.VirtualMachine$ForHotSpot$OnUnix
...
logback-core-1.2.3.jar (3 errors):
  org.codehaus.janino.ScriptEvaluator is not found, referenced from ch.qos.logback.core.boolex.JaninoEventEvaluatorBase
  org.codehaus.janino.ClassBodyEvaluator is not found, referenced from ch.qos.logback.core.joran.conditional.PropertyEvalScriptBuilder
  org.codehaus.commons.compiler.CompileException is not found, referenced from ch.qos.logback.core.joran.conditional.PropertyEvalScriptBuilder
  org.codehaus.janino.ScriptEvaluator.<init> is not found, referenced from ch.qos.logback.core.boolex.JaninoEventEvaluatorBase
  org.codehaus.janino.ScriptEvaluator.evaluate is not found, referenced from ch.qos.logback.core.boolex.JaninoEventEvaluatorBase


...
```

**Comment by suztomo** [comment] 2019-04-30 19:09
# Result

## reactor package

[Spring-core artifact](https://search.maven.org/artifact/org.springframework/spring-core/5.1.6.RELEASE/jar) has optional dependency to reactor-core:
```
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-core</artifactId>
      <version>3.2.8.RELEASE</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
```

Because this reactor-core is not direct dependency, the dependency was omitted.

**Comment by chingor13** [comment] 2019-04-30 20:44
This is the same issue I'm seeing with our transitive dependency upon `commons-logging:commons-logging:1.2`. It declares optional dependencies upon `log4j`, `logkit`, and `avalon-framework`.

**Comment by suztomo** [comment] 2019-05-01 14:35
@chingor13 Thank you for sharing observation. I'll update you once these issues are resolved.

**Comment by elharo** [comment] 2021-07-22 14:35
@suztomo Is this a dupe of #1983?

**Closed by elharo** 2021-07-22 14:35 UTC

**Comment by suztomo** [comment] 2021-07-22 15:19
Yes.
