### ISSUE TITLE
Create a left sidebar for easier navigation

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/cloud-opensource-java#1033] opened 2019-11-12 21:30 UTC
A left sidebar would make it a lot easier to navigate through the JLBP entries.

**Comment by elharo** [comment] 2021-07-22 13:39
dupe of #855

**Closed by elharo** 2021-07-22 13:39 UTC
Labels: best practices, p3

**Comment by garrettjonesgoogle** [comment] 2021-07-22 14:56
This has nothing to do with #855, which is a pull request

**Comment by elharo** [comment] 2021-07-22 15:05
Make that #885
